-- Generated from live production schema introspection (2026-07-20). Do not hand-edit column/RLS/trigger/function bodies — regenerate from source instead.

ALTER TABLE compliance."activity_logs" ADD CONSTRAINT "activity_logs_pkey" PRIMARY KEY ("log_id", "created_at");
ALTER TABLE core."admins" ADD CONSTRAINT "admins_pkey" PRIMARY KEY ("admin_id");
ALTER TABLE ops."alembic_version" ADD CONSTRAINT "alembic_version_pkey" PRIMARY KEY ("version_num");
ALTER TABLE core."anamnesis_assessments" ADD CONSTRAINT "anamnesis_assessments_pkey" PRIMARY KEY ("anamnesis_id");
ALTER TABLE reference."anamnesis_options" ADD CONSTRAINT "anamnesis_options_pkey" PRIMARY KEY ("option_id");
ALTER TABLE reference."anamnesis_questions" ADD CONSTRAINT "anamnesis_questions_pkey" PRIMARY KEY ("question_id");
ALTER TABLE core."anamnesis_responses" ADD CONSTRAINT "anamnesis_responses_pkey" PRIMARY KEY ("response_id");
ALTER TABLE core."appointment_audit_logs" ADD CONSTRAINT "appointment_audit_logs_pkey" PRIMARY KEY ("audit_id", "changed_at");
ALTER TABLE core."appointment_requests" ADD CONSTRAINT "appointment_requests_pkey" PRIMARY KEY ("request_id");
ALTER TABLE core."appointments" ADD CONSTRAINT "appointments_pkey" PRIMARY KEY ("appointment_id");
ALTER TABLE core."assessment_protocol_requests" ADD CONSTRAINT "assessment_protocol_requests_pkey" PRIMARY KEY ("request_id");
ALTER TABLE compliance."audit_logs" ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("log_id", "changed_at");
ALTER TABLE core."ca_doctor_assignments" ADD CONSTRAINT "ca_doctor_assignments_pkey" PRIMARY KEY ("cda_id");
ALTER TABLE core."clinic_requests" ADD CONSTRAINT "clinic_requests_pkey" PRIMARY KEY ("request_id");
ALTER TABLE core."clinic_staff_assignments" ADD CONSTRAINT "clinic_staff_assignments_pkey" PRIMARY KEY ("assignment_id");
ALTER TABLE core."clinical_assistants" ADD CONSTRAINT "clinical_assistants_pkey" PRIMARY KEY ("ca_id");
ALTER TABLE core."clinics" ADD CONSTRAINT "clinics_pkey" PRIMARY KEY ("clinic_id");
ALTER TABLE compliance."consent_records" ADD CONSTRAINT "consent_records_pkey" PRIMARY KEY ("consent_id");
ALTER TABLE reference."consent_templates" ADD CONSTRAINT "consent_templates_pkey" PRIMARY KEY ("template_id");
ALTER TABLE core."device_assignments" ADD CONSTRAINT "device_assignments_pkey" PRIMARY KEY ("da_id");
ALTER TABLE core."doctor_patient_assignments" ADD CONSTRAINT "doctor_patient_assignments_pkey" PRIMARY KEY ("assignment_id");
ALTER TABLE core."doctor_schedule_overrides" ADD CONSTRAINT "doctor_schedule_overrides_pkey" PRIMARY KEY ("override_id");
ALTER TABLE core."doctor_session_notes" ADD CONSTRAINT "doctor_session_notes_pkey" PRIMARY KEY ("note_id");
ALTER TABLE core."doctor_weekly_schedules" ADD CONSTRAINT "doctor_weekly_schedules_pkey" PRIMARY KEY ("schedule_id");
ALTER TABLE core."doctors" ADD CONSTRAINT "doctors_pkey" PRIMARY KEY ("doctor_id");
ALTER TABLE core."inventory" ADD CONSTRAINT "inventory_pkey" PRIMARY KEY ("inventory_id");
ALTER TABLE core."notifications" ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("notification_id", "created_at");
ALTER TABLE core."order_items" ADD CONSTRAINT "order_items_pkey" PRIMARY KEY ("item_id");
ALTER TABLE ops."outbox_events" ADD CONSTRAINT "outbox_events_pkey" PRIMARY KEY ("outbox_id");
ALTER TABLE core."patient_clinic_transfers" ADD CONSTRAINT "patient_clinic_transfers_pkey" PRIMARY KEY ("pct_id");
ALTER TABLE core."patient_disease_selection" ADD CONSTRAINT "patient_disease_selection_pkey" PRIMARY KEY ("pds_id");
ALTER TABLE core."patient_eeg_files" ADD CONSTRAINT "patient_eeg_files_pkey" PRIMARY KEY ("eeg_id");
ALTER TABLE core."patient_medical_history_files" ADD CONSTRAINT "patient_medical_history_files_pkey" PRIMARY KEY ("mhf_id");
ALTER TABLE core."patient_scale_assignments" ADD CONSTRAINT "patient_scale_assignments_pkey" PRIMARY KEY ("psa_id");
ALTER TABLE core."patients" ADD CONSTRAINT "patients_pkey" PRIMARY KEY ("patient_id");
ALTER TABLE core."payments" ADD CONSTRAINT "payments_pkey" PRIMARY KEY ("payment_id");
ALTER TABLE reference."products" ADD CONSTRAINT "products_pkey" PRIMARY KEY ("product_id");
ALTER TABLE core."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");
ALTER TABLE core."prs_assessment_instances" ADD CONSTRAINT "prs_assessment_instances_pkey" PRIMARY KEY ("instance_id");
ALTER TABLE reference."prs_disease_question_map" ADD CONSTRAINT "prs_disease_question_map_pkey" PRIMARY KEY ("dq_map_id");
ALTER TABLE reference."prs_disease_scale_map" ADD CONSTRAINT "prs_disease_scale_map_pkey" PRIMARY KEY ("ds_map_id");
ALTER TABLE reference."prs_diseases" ADD CONSTRAINT "prs_diseases_pkey" PRIMARY KEY ("disease_id");
ALTER TABLE core."prs_final_results" ADD CONSTRAINT "prs_final_results_pkey" PRIMARY KEY ("final_result_id");
ALTER TABLE reference."prs_option_translations" ADD CONSTRAINT "prs_option_translations_pkey" PRIMARY KEY ("option_id", "language_code");
ALTER TABLE reference."prs_options" ADD CONSTRAINT "prs_options_pkey" PRIMARY KEY ("option_id");
ALTER TABLE reference."prs_question_translations" ADD CONSTRAINT "prs_question_translations_pkey" PRIMARY KEY ("question_id", "language_code");
ALTER TABLE reference."prs_questions" ADD CONSTRAINT "prs_questions_pkey" PRIMARY KEY ("question_id");
ALTER TABLE core."prs_responses" ADD CONSTRAINT "prs_responses_pkey" PRIMARY KEY ("response_id");
ALTER TABLE reference."prs_scale_question_map" ADD CONSTRAINT "prs_scale_question_map_pkey" PRIMARY KEY ("sq_map_id");
ALTER TABLE core."prs_scale_results" ADD CONSTRAINT "prs_scale_results_pkey" PRIMARY KEY ("scale_result_id");
ALTER TABLE reference."prs_scales" ADD CONSTRAINT "prs_scales_pkey" PRIMARY KEY ("scale_id");
ALTER TABLE core."receptionists" ADD CONSTRAINT "receptionists_pkey" PRIMARY KEY ("receptionist_id");
ALTER TABLE core."regions" ADD CONSTRAINT "regions_pkey" PRIMARY KEY ("region_id");
ALTER TABLE ops."schema_migrations" ADD CONSTRAINT "schema_migrations_pkey" PRIMARY KEY ("version");
ALTER TABLE core."sessions" ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("session_id");
ALTER TABLE core."staff_requests" ADD CONSTRAINT "staff_requests_pkey" PRIMARY KEY ("request_id");
ALTER TABLE core."stock_transfers" ADD CONSTRAINT "stock_transfers_pkey" PRIMARY KEY ("st_id");
ALTER TABLE core."store_orders" ADD CONSTRAINT "store_orders_pkey" PRIMARY KEY ("order_id");
ALTER TABLE core."treatment_cycles" ADD CONSTRAINT "treatment_cycles_pkey" PRIMARY KEY ("cycle_id");
ALTER TABLE core."treatment_plans" ADD CONSTRAINT "treatment_plans_pkey" PRIMARY KEY ("plan_id");
ALTER TABLE core."treatment_sessions" ADD CONSTRAINT "treatment_sessions_pkey" PRIMARY KEY ("ts_id", "created_at");
