-- Generated from live production schema introspection (2026-07-20). Do not hand-edit column/RLS/trigger/function bodies — regenerate from source instead.

ALTER TABLE core."admins" ADD CONSTRAINT "admins_profile_id_key" UNIQUE ("profile_id");
ALTER TABLE core."anamnesis_assessments" ADD CONSTRAINT "anamnesis_assessments_patient_id_version_key" UNIQUE ("patient_id", "version");
ALTER TABLE reference."anamnesis_options" ADD CONSTRAINT "anamnesis_options_question_id_option_value_key" UNIQUE ("question_id", "option_value");
ALTER TABLE reference."anamnesis_questions" ADD CONSTRAINT "anamnesis_questions_question_code_key" UNIQUE ("question_code");
ALTER TABLE core."ca_doctor_assignments" ADD CONSTRAINT "ca_doctor_assignments_ca_id_doctor_id_key" UNIQUE ("ca_id", "doctor_id");
ALTER TABLE core."clinic_staff_assignments" ADD CONSTRAINT "clinic_staff_assignments_clinic_id_profile_id_key" UNIQUE ("clinic_id", "profile_id");
ALTER TABLE core."clinical_assistants" ADD CONSTRAINT "clinical_assistants_profile_id_key" UNIQUE ("profile_id");
ALTER TABLE core."clinics" ADD CONSTRAINT "clinics_clinic_code_key" UNIQUE ("clinic_code");
ALTER TABLE reference."consent_templates" ADD CONSTRAINT "uq_consent_templates_type_role_version" UNIQUE ("consent_type", "role", "version");
ALTER TABLE core."doctor_schedule_overrides" ADD CONSTRAINT "doctor_schedule_overrides_doctor_id_override_date_key" UNIQUE ("doctor_id", "override_date");
ALTER TABLE core."doctor_session_notes" ADD CONSTRAINT "doctor_session_notes_session_id_doctor_id_session_phase_key" UNIQUE ("session_id", "doctor_id", "session_phase");
ALTER TABLE core."doctor_weekly_schedules" ADD CONSTRAINT "doctor_weekly_schedules_doctor_id_clinic_id_day_of_week_key" UNIQUE ("doctor_id", "clinic_id", "day_of_week");
ALTER TABLE core."doctors" ADD CONSTRAINT "doctors_profile_id_key" UNIQUE ("profile_id");
ALTER TABLE core."inventory" ADD CONSTRAINT "inventory_product_id_clinic_id_key" UNIQUE ("product_id", "clinic_id");
ALTER TABLE core."patient_eeg_files" ADD CONSTRAINT "patient_eeg_files_raw_data_s3_key_key" UNIQUE ("raw_data_s3_key");
ALTER TABLE core."patient_eeg_files" ADD CONSTRAINT "patient_eeg_files_report_s3_key_key" UNIQUE ("report_s3_key");
ALTER TABLE core."patient_medical_history_files" ADD CONSTRAINT "patient_medical_history_files_s3_key_key" UNIQUE ("s3_key");
ALTER TABLE core."patients" ADD CONSTRAINT "patients_mrn_key" UNIQUE ("mrn");
ALTER TABLE core."patients" ADD CONSTRAINT "patients_profile_id_key" UNIQUE ("profile_id");
ALTER TABLE core."payments" ADD CONSTRAINT "payments_idempotency_key_key" UNIQUE ("idempotency_key");
ALTER TABLE core."payments" ADD CONSTRAINT "payments_razorpay_order_id_key" UNIQUE ("razorpay_order_id");
ALTER TABLE core."payments" ADD CONSTRAINT "payments_razorpay_payment_id_key" UNIQUE ("razorpay_payment_id");
ALTER TABLE reference."products" ADD CONSTRAINT "products_sku_key" UNIQUE ("sku");
ALTER TABLE core."profiles" ADD CONSTRAINT "profiles_cognito_sub_key" UNIQUE ("cognito_sub");
ALTER TABLE core."profiles" ADD CONSTRAINT "profiles_email_key" UNIQUE ("email");
ALTER TABLE reference."prs_disease_question_map" ADD CONSTRAINT "prs_disease_question_map_disease_id_question_id_key" UNIQUE ("disease_id", "question_id");
ALTER TABLE reference."prs_disease_scale_map" ADD CONSTRAINT "prs_disease_scale_map_disease_id_scale_id_key" UNIQUE ("disease_id", "scale_id");
ALTER TABLE reference."prs_diseases" ADD CONSTRAINT "prs_diseases_disease_code_key" UNIQUE ("disease_code");
ALTER TABLE core."prs_final_results" ADD CONSTRAINT "prs_final_results_instance_id_key" UNIQUE ("instance_id");
ALTER TABLE reference."prs_options" ADD CONSTRAINT "prs_options_question_id_option_value_key" UNIQUE ("question_id", "option_value");
ALTER TABLE reference."prs_questions" ADD CONSTRAINT "prs_questions_question_code_key" UNIQUE ("question_code");
ALTER TABLE core."prs_responses" ADD CONSTRAINT "prs_responses_instance_id_question_id_key" UNIQUE ("instance_id", "question_id");
ALTER TABLE reference."prs_scale_question_map" ADD CONSTRAINT "prs_scale_question_map_scale_id_question_id_key" UNIQUE ("scale_id", "question_id");
ALTER TABLE core."prs_scale_results" ADD CONSTRAINT "prs_scale_results_instance_id_scale_id_key" UNIQUE ("instance_id", "scale_id");
ALTER TABLE reference."prs_scales" ADD CONSTRAINT "prs_scales_scale_code_key" UNIQUE ("scale_code");
ALTER TABLE core."receptionists" ADD CONSTRAINT "receptionists_profile_id_key" UNIQUE ("profile_id");
ALTER TABLE core."regions" ADD CONSTRAINT "regions_country_state_key" UNIQUE ("country", "state");
