-- Generated from live production schema introspection (2026-07-20). Do not hand-edit column/RLS/trigger/function bodies — regenerate from source instead.

CREATE INDEX idx_actlog_actor_id ON compliance."activity_logs" USING btree (actor_id);
CREATE INDEX idx_actlog_category ON compliance."activity_logs" USING btree (category);
CREATE INDEX idx_actlog_clinic_id ON compliance."activity_logs" USING btree (clinic_id);
CREATE INDEX idx_actlog_created_at_brin ON compliance."activity_logs" USING brin (created_at);
CREATE INDEX idx_actlog_entity_id ON compliance."activity_logs" USING btree (entity_id);
CREATE INDEX idx_actlog_event_type ON compliance."activity_logs" USING btree (event_type);
CREATE INDEX idx_actlog_metadata_gin ON compliance."activity_logs" USING gin (metadata);
CREATE INDEX idx_actlog_region_id ON compliance."activity_logs" USING btree (region_id);
CREATE INDEX idx_actlog_request_id ON compliance."activity_logs" USING btree (request_id);
CREATE INDEX idx_admins_admin_type ON core."admins" USING btree (admin_type);
CREATE INDEX idx_admins_clinic_id ON core."admins" USING btree (clinic_id);
CREATE INDEX idx_admins_region_id ON core."admins" USING btree (region_id);
CREATE UNIQUE INDEX alembic_version_pkc ON ops."alembic_version" USING btree (version_num);
CREATE INDEX idx_anamnesis_cycle_id ON core."anamnesis_assessments" USING btree (cycle_id);
CREATE INDEX idx_anamnesis_patient_id ON core."anamnesis_assessments" USING btree (patient_id);
CREATE INDEX idx_anamnesis_status ON core."anamnesis_assessments" USING btree (status);
CREATE INDEX idx_anamnesis_submitted_by ON core."anamnesis_assessments" USING btree (submitted_by);
CREATE INDEX idx_anao_question_id ON reference."anamnesis_options" USING btree (question_id);
CREATE INDEX idx_anaq_depends_on ON reference."anamnesis_questions" USING btree (depends_on_question_id);
CREATE INDEX idx_anaq_section_number ON reference."anamnesis_questions" USING btree (section_number);
CREATE INDEX idx_anaq_status ON reference."anamnesis_questions" USING btree (status);
CREATE INDEX idx_anar_anamnesis_id ON core."anamnesis_responses" USING btree (anamnesis_id);
CREATE INDEX idx_anar_question_id ON core."anamnesis_responses" USING btree (question_id);
CREATE INDEX idx_apal_appointment_id ON core."appointment_audit_logs" USING btree (appointment_id);
CREATE INDEX idx_apal_changed_at_brin ON core."appointment_audit_logs" USING brin (changed_at);
CREATE INDEX idx_areq_clinic_status ON core."appointment_requests" USING btree (clinic_id, status);
CREATE INDEX idx_areq_doctor_status ON core."appointment_requests" USING btree (doctor_id, status);
CREATE INDEX idx_areq_patient_status ON core."appointment_requests" USING btree (patient_id, status);
CREATE INDEX idx_areq_pref_date1 ON core."appointment_requests" USING btree (preferred_date_1);
CREATE INDEX idx_areq_urgency ON core."appointment_requests" USING btree (urgency) WHERE (urgency = ANY (ARRAY['urgent'::text, 'emergency'::text]));
CREATE INDEX idx_appt_clinic_date_status ON core."appointments" USING btree (clinic_id, appointment_date, status);
CREATE INDEX idx_appt_cycle_id ON core."appointments" USING btree (cycle_id);
CREATE INDEX idx_appt_doctor_date_status ON core."appointments" USING btree (doctor_id, appointment_date, status);
CREATE INDEX idx_appt_patient_date ON core."appointments" USING btree (patient_id, appointment_date DESC);
CREATE INDEX idx_appt_request_id ON core."appointments" USING btree (appointment_request_id);
CREATE INDEX idx_appt_session_id ON core."appointments" USING btree (session_id);
CREATE INDEX idx_appt_status ON core."appointments" USING btree (status);
CREATE INDEX idx_apr_ca_id ON core."assessment_protocol_requests" USING btree (clinical_assistant_id);
CREATE INDEX idx_apr_cycle_id ON core."assessment_protocol_requests" USING btree (cycle_id);
CREATE INDEX idx_apr_doctor_id ON core."assessment_protocol_requests" USING btree (doctor_id);
CREATE INDEX idx_apr_patient_id ON core."assessment_protocol_requests" USING btree (patient_id);
CREATE INDEX idx_apr_status ON core."assessment_protocol_requests" USING btree (status);
CREATE INDEX idx_al_changed_at_brin ON compliance."audit_logs" USING brin (changed_at);
CREATE INDEX idx_al_changed_by ON compliance."audit_logs" USING btree (changed_by);
CREATE INDEX idx_al_operation ON compliance."audit_logs" USING btree (operation);
CREATE INDEX idx_al_record_id ON compliance."audit_logs" USING btree (record_id);
CREATE INDEX idx_al_table_name ON compliance."audit_logs" USING btree (table_name);
CREATE INDEX idx_cda_ca_id ON core."ca_doctor_assignments" USING btree (ca_id);
CREATE INDEX idx_cda_clinic_id ON core."ca_doctor_assignments" USING btree (clinic_id);
CREATE INDEX idx_cda_doctor_id ON core."ca_doctor_assignments" USING btree (doctor_id);
CREATE INDEX idx_clinic_req_clinic_id ON core."clinic_requests" USING btree (clinic_id);
CREATE INDEX idx_clinic_req_payload_gin ON core."clinic_requests" USING gin (payload);
CREATE INDEX idx_clinic_req_pending ON core."clinic_requests" USING btree (region_id, created_at DESC) WHERE (status = 'pending'::text);
CREATE INDEX idx_clinic_req_region_id ON core."clinic_requests" USING btree (region_id);
CREATE INDEX idx_clinic_req_status ON core."clinic_requests" USING btree (status);
CREATE INDEX idx_clinic_req_submitted_by ON core."clinic_requests" USING btree (submitted_by);
CREATE INDEX idx_csa_active ON core."clinic_staff_assignments" USING btree (clinic_id, profile_id) WHERE (is_active = true);
CREATE INDEX idx_csa_clinic_id ON core."clinic_staff_assignments" USING btree (clinic_id);
CREATE INDEX idx_csa_is_active ON core."clinic_staff_assignments" USING btree (is_active);
CREATE INDEX idx_csa_profile_id ON core."clinic_staff_assignments" USING btree (profile_id);
CREATE INDEX idx_csa_staff_role ON core."clinic_staff_assignments" USING btree (staff_role);
CREATE INDEX idx_ca_profile_id ON core."clinical_assistants" USING btree (profile_id);
CREATE INDEX idx_clinics_clinic_admin ON core."clinics" USING btree (clinic_admin_id);
CREATE INDEX idx_clinics_is_main_branch ON core."clinics" USING btree (is_main_branch);
CREATE UNIQUE INDEX idx_clinics_one_main_branch ON core."clinics" USING btree (region_id) WHERE (is_main_branch = true);
CREATE INDEX idx_clinics_region_id ON core."clinics" USING btree (region_id);
CREATE INDEX idx_clinics_status ON core."clinics" USING btree (status);
CREATE INDEX idx_cr_clinic_id ON compliance."consent_records" USING btree (clinic_id);
CREATE INDEX idx_cr_consent_type ON compliance."consent_records" USING btree (consent_type);
CREATE INDEX idx_cr_patient_id ON compliance."consent_records" USING btree (patient_id);
CREATE INDEX idx_cr_staff_id ON compliance."consent_records" USING btree (staff_id);
CREATE INDEX idx_cr_status ON compliance."consent_records" USING btree (status);
CREATE INDEX idx_cr_template_id ON compliance."consent_records" USING btree (template_id);
CREATE INDEX idx_ct_consent_type ON reference."consent_templates" USING btree (consent_type);
CREATE INDEX idx_ct_is_active ON reference."consent_templates" USING btree (is_active);
CREATE INDEX idx_da_clinic_id ON core."device_assignments" USING btree (clinic_id);
CREATE INDEX idx_da_order_id ON core."device_assignments" USING btree (order_id);
CREATE INDEX idx_da_patient_id ON core."device_assignments" USING btree (patient_id);
CREATE INDEX idx_da_plan_id ON core."device_assignments" USING btree (plan_id);
CREATE INDEX idx_da_purchase_status ON core."device_assignments" USING btree (purchase_status);
CREATE INDEX idx_dpa_active_doctor ON core."doctor_patient_assignments" USING btree (doctor_id) WHERE (status = 'active'::text);
CREATE UNIQUE INDEX idx_dpa_active_unique ON core."doctor_patient_assignments" USING btree (doctor_id, patient_id) WHERE (status = 'active'::text);
CREATE INDEX idx_dpa_clinic_id ON core."doctor_patient_assignments" USING btree (clinic_id);
CREATE INDEX idx_dpa_doctor_id ON core."doctor_patient_assignments" USING btree (doctor_id);
CREATE INDEX idx_dpa_patient_id ON core."doctor_patient_assignments" USING btree (patient_id);
CREATE INDEX idx_dpa_status ON core."doctor_patient_assignments" USING btree (status);
CREATE INDEX idx_dso_clinic ON core."doctor_schedule_overrides" USING btree (clinic_id);
CREATE INDEX idx_dso_date ON core."doctor_schedule_overrides" USING btree (override_date);
CREATE INDEX idx_dso_doctor_date ON core."doctor_schedule_overrides" USING btree (doctor_id, override_date);
CREATE INDEX idx_dsn_cycle_id ON core."doctor_session_notes" USING btree (cycle_id);
CREATE INDEX idx_dsn_doctor_id ON core."doctor_session_notes" USING btree (doctor_id);
CREATE INDEX idx_dsn_patient_id ON core."doctor_session_notes" USING btree (patient_id);
CREATE INDEX idx_dsn_patient_session ON core."doctor_session_notes" USING btree (patient_id, session_number);
CREATE INDEX idx_dsn_session_id ON core."doctor_session_notes" USING btree (session_id);
CREATE INDEX idx_dsn_session_phase ON core."doctor_session_notes" USING btree (session_phase);
CREATE INDEX idx_dws_clinic_dow ON core."doctor_weekly_schedules" USING btree (clinic_id, day_of_week);
CREATE INDEX idx_dws_doctor_clinic ON core."doctor_weekly_schedules" USING btree (doctor_id, clinic_id);
CREATE INDEX idx_dws_is_active ON core."doctor_weekly_schedules" USING btree (is_active);
CREATE INDEX idx_doctors_availability_status ON core."doctors" USING btree (availability_status);
CREATE INDEX idx_doctors_clinic_id ON core."doctors" USING btree (clinic_id);
CREATE INDEX idx_doctors_profile_id ON core."doctors" USING btree (profile_id);
CREATE INDEX idx_inventory_clinic_id ON core."inventory" USING btree (clinic_id);
CREATE INDEX idx_inventory_product_id ON core."inventory" USING btree (product_id);
CREATE INDEX idx_notif_clinic_id ON core."notifications" USING btree (clinic_id);
CREATE INDEX idx_notif_created_at ON core."notifications" USING btree (created_at DESC);
CREATE INDEX idx_notif_recipient_id ON core."notifications" USING btree (recipient_id);
CREATE INDEX idx_notif_sender_id ON core."notifications" USING btree (sender_id);
CREATE INDEX idx_notif_type ON core."notifications" USING btree (type);
CREATE INDEX idx_notif_unread ON core."notifications" USING btree (recipient_id, created_at DESC) WHERE (is_read = false);
CREATE INDEX idx_oi_order_id ON core."order_items" USING btree (order_id);
CREATE INDEX idx_oi_product_id ON core."order_items" USING btree (product_id);
CREATE INDEX idx_outbox_unpublished ON ops."outbox_events" USING btree (created_at) WHERE (published_at IS NULL);
CREATE INDEX idx_pct_active_cycle_id ON core."patient_clinic_transfers" USING btree (active_cycle_id);
CREATE INDEX idx_pct_from_clinic_id ON core."patient_clinic_transfers" USING btree (from_clinic_id);
CREATE UNIQUE INDEX idx_pct_no_dup_pending ON core."patient_clinic_transfers" USING btree (patient_id, from_clinic_id, to_clinic_id) WHERE (status = ANY (ARRAY['pending'::text, 'consented'::text]));
CREATE INDEX idx_pct_patient_id ON core."patient_clinic_transfers" USING btree (patient_id);
CREATE INDEX idx_pct_status ON core."patient_clinic_transfers" USING btree (status);
CREATE INDEX idx_pct_to_clinic_id ON core."patient_clinic_transfers" USING btree (to_clinic_id);
CREATE INDEX idx_pct_transfer_reason ON core."patient_clinic_transfers" USING btree (transfer_reason);
CREATE INDEX idx_pds_disease_id ON core."patient_disease_selection" USING btree (disease_id);
CREATE UNIQUE INDEX idx_pds_patient_disease_unique ON core."patient_disease_selection" USING btree (patient_id, disease_id) WHERE (disease_id IS NOT NULL);
CREATE INDEX idx_pds_patient_id ON core."patient_disease_selection" USING btree (patient_id);
CREATE INDEX idx_eeg_clinic_id ON core."patient_eeg_files" USING btree (clinic_id);
CREATE INDEX idx_eeg_cycle_id ON core."patient_eeg_files" USING btree (cycle_id);
CREATE INDEX idx_eeg_eeg_type ON core."patient_eeg_files" USING btree (eeg_type);
CREATE INDEX idx_eeg_is_abnormal ON core."patient_eeg_files" USING btree (is_abnormal);
CREATE INDEX idx_eeg_patient_id ON core."patient_eeg_files" USING btree (patient_id);
CREATE INDEX idx_eeg_performed_at ON core."patient_eeg_files" USING btree (performed_at DESC);
CREATE INDEX idx_eeg_performed_by ON core."patient_eeg_files" USING btree (performed_by);
CREATE INDEX idx_eeg_reviewed_by ON core."patient_eeg_files" USING btree (reviewed_by);
CREATE INDEX idx_eeg_session_id ON core."patient_eeg_files" USING btree (session_id);
CREATE INDEX idx_eeg_status ON core."patient_eeg_files" USING btree (status);
CREATE INDEX idx_mhf_clinic_id ON core."patient_medical_history_files" USING btree (clinic_id);
CREATE INDEX idx_mhf_cycle_id ON core."patient_medical_history_files" USING btree (cycle_id);
CREATE INDEX idx_mhf_document_date ON core."patient_medical_history_files" USING btree (document_date DESC);
CREATE INDEX idx_mhf_document_type ON core."patient_medical_history_files" USING btree (document_type);
CREATE INDEX idx_mhf_is_deleted ON core."patient_medical_history_files" USING btree (is_deleted);
CREATE INDEX idx_mhf_patient_id ON core."patient_medical_history_files" USING btree (patient_id);
CREATE INDEX idx_mhf_uploaded_by ON core."patient_medical_history_files" USING btree (uploaded_by);
CREATE INDEX idx_psa_assessment_stage ON core."patient_scale_assignments" USING btree (assessment_stage);
CREATE INDEX idx_psa_patient_id ON core."patient_scale_assignments" USING btree (patient_id);
CREATE INDEX idx_psa_scale_id ON core."patient_scale_assignments" USING btree (scale_id);
CREATE INDEX idx_patients_primary_clinic_id ON core."patients" USING btree (primary_clinic_id);
CREATE INDEX idx_patients_primary_doctor_id ON core."patients" USING btree (primary_doctor_id);
CREATE INDEX idx_patients_profile_id ON core."patients" USING btree (profile_id);
CREATE INDEX idx_patients_registration_status ON core."patients" USING btree (registration_status);
CREATE INDEX idx_payments_order_id ON core."payments" USING btree (order_id);
CREATE INDEX idx_payments_session_id ON core."payments" USING btree (session_id);
CREATE INDEX idx_payments_status ON core."payments" USING btree (status);
CREATE INDEX idx_products_category ON reference."products" USING btree (category);
CREATE INDEX idx_products_is_active ON reference."products" USING btree (is_active);
CREATE INDEX idx_profiles_is_active ON core."profiles" USING btree (is_active);
CREATE INDEX idx_profiles_role ON core."profiles" USING btree (role);
CREATE INDEX idx_pai_assessment_stage ON core."prs_assessment_instances" USING btree (assessment_stage);
CREATE INDEX idx_pai_cycle_id ON core."prs_assessment_instances" USING btree (cycle_id);
CREATE INDEX idx_pai_disease_id ON core."prs_assessment_instances" USING btree (disease_id);
CREATE INDEX idx_pai_patient_id ON core."prs_assessment_instances" USING btree (patient_id);
CREATE INDEX idx_pai_session_id ON core."prs_assessment_instances" USING btree (session_id);
CREATE INDEX idx_pai_status ON core."prs_assessment_instances" USING btree (status);
CREATE INDEX idx_ot_lang ON reference."prs_option_translations" USING btree (language_code);
CREATE INDEX idx_qt_lang ON reference."prs_question_translations" USING btree (language_code);
CREATE INDEX idx_prs_questions_scale_id ON reference."prs_questions" USING btree (scale_id);
CREATE INDEX idx_prs_resp_instance_id ON core."prs_responses" USING btree (instance_id);
CREATE INDEX idx_prs_resp_question_id ON core."prs_responses" USING btree (question_id);
CREATE INDEX idx_prs_scales_applicable_for ON reference."prs_scales" USING btree (applicable_for);
CREATE INDEX idx_prs_scales_is_common ON reference."prs_scales" USING btree (is_common_scale);
CREATE INDEX idx_regions_is_active ON core."regions" USING btree (is_active);
CREATE INDEX idx_regions_regional_admin ON core."regions" USING btree (regional_admin_id);
CREATE INDEX idx_sessions_ca_id ON core."sessions" USING btree (ca_id);
CREATE INDEX idx_sessions_clinic_id ON core."sessions" USING btree (clinic_id);
CREATE INDEX idx_sessions_cycle_id ON core."sessions" USING btree (cycle_id);
CREATE INDEX idx_sessions_doctor_id ON core."sessions" USING btree (doctor_id);
CREATE INDEX idx_sessions_patient_date ON core."sessions" USING btree (patient_id, session_date DESC);
CREATE INDEX idx_sessions_patient_id ON core."sessions" USING btree (patient_id);
CREATE INDEX idx_sessions_payment_status ON core."sessions" USING btree (payment_status);
CREATE INDEX idx_sessions_session_date ON core."sessions" USING btree (session_date);
CREATE INDEX idx_sessions_session_phase ON core."sessions" USING btree (session_phase);
CREATE INDEX idx_sessions_session_type ON core."sessions" USING btree (session_type);
CREATE INDEX idx_sessions_status ON core."sessions" USING btree (status);
CREATE INDEX idx_staff_req_clinic_id ON core."staff_requests" USING btree (clinic_id);
CREATE INDEX idx_staff_req_cred_gin ON core."staff_requests" USING gin (candidate_credentials);
CREATE INDEX idx_staff_req_position_role ON core."staff_requests" USING btree (position_role);
CREATE INDEX idx_staff_req_status ON core."staff_requests" USING btree (status);
CREATE INDEX idx_staff_req_submitted_by ON core."staff_requests" USING btree (submitted_by);
CREATE INDEX idx_st_from_clinic_id ON core."stock_transfers" USING btree (from_clinic_id);
CREATE INDEX idx_st_order_id ON core."stock_transfers" USING btree (order_id);
CREATE INDEX idx_st_product_id ON core."stock_transfers" USING btree (product_id);
CREATE INDEX idx_st_status ON core."stock_transfers" USING btree (status);
CREATE INDEX idx_st_to_clinic_id ON core."stock_transfers" USING btree (to_clinic_id);
CREATE INDEX idx_so_clinic_id ON core."store_orders" USING btree (clinic_id);
CREATE INDEX idx_so_initiated_by ON core."store_orders" USING btree (initiated_by);
CREATE INDEX idx_so_order_type ON core."store_orders" USING btree (order_type);
CREATE INDEX idx_so_patient_id ON core."store_orders" USING btree (patient_id);
CREATE INDEX idx_so_plan_id ON core."store_orders" USING btree (treatment_plan_id);
CREATE INDEX idx_so_status ON core."store_orders" USING btree (status);
CREATE INDEX idx_cycles_clinic_id ON core."treatment_cycles" USING btree (clinic_id);
CREATE INDEX idx_cycles_cycle_type ON core."treatment_cycles" USING btree (cycle_type);
CREATE INDEX idx_cycles_doctor_id ON core."treatment_cycles" USING btree (doctor_id);
CREATE INDEX idx_cycles_patient_id ON core."treatment_cycles" USING btree (patient_id);
CREATE INDEX idx_cycles_status ON core."treatment_cycles" USING btree (status);
CREATE INDEX idx_tp_cycle_id ON core."treatment_plans" USING btree (cycle_id);
CREATE INDEX idx_tp_doctor_id ON core."treatment_plans" USING btree (doctor_id);
CREATE INDEX idx_tp_parent_plan_id ON core."treatment_plans" USING btree (parent_plan_id);
CREATE INDEX idx_tp_patient_id ON core."treatment_plans" USING btree (patient_id);
CREATE INDEX idx_tp_protocol_gin ON core."treatment_plans" USING gin (protocol_details);
CREATE INDEX idx_tp_status ON core."treatment_plans" USING btree (status);
CREATE INDEX idx_ts_billing_type ON core."treatment_sessions" USING btree (billing_type);
CREATE INDEX idx_ts_ca_id ON core."treatment_sessions" USING btree (ca_id);
CREATE INDEX idx_ts_patient_id ON core."treatment_sessions" USING btree (patient_id);
CREATE INDEX idx_ts_payment_status ON core."treatment_sessions" USING btree (payment_status);
CREATE INDEX idx_ts_plan_id ON core."treatment_sessions" USING btree (plan_id);
CREATE INDEX idx_ts_session_id ON core."treatment_sessions" USING btree (session_id);
CREATE INDEX idx_ts_status ON core."treatment_sessions" USING btree (status);
