-- Generated from live production schema introspection (2026-07-20). Do not hand-edit column/RLS/trigger/function bodies — regenerate from source instead.

CREATE TRIGGER trg_audit_admins AFTER INSERT OR DELETE OR UPDATE ON core."admins" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('admin_id');
CREATE TRIGGER trg_audit_anamnesis_assessments AFTER INSERT OR DELETE OR UPDATE ON core."anamnesis_assessments" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('anamnesis_id');
CREATE TRIGGER trg_updated_at_anamnesis_assessments BEFORE UPDATE ON core."anamnesis_assessments" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_updated_at_anamnesis_responses BEFORE UPDATE ON core."anamnesis_responses" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_appointment_requests AFTER INSERT OR DELETE OR UPDATE ON core."appointment_requests" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('request_id');
CREATE TRIGGER trg_updated_at_appointment_requests BEFORE UPDATE ON core."appointment_requests" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_appointments AFTER INSERT OR DELETE OR UPDATE ON core."appointments" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('appointment_id');
CREATE TRIGGER trg_updated_at_appointments BEFORE UPDATE ON core."appointments" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_assessment_protocol_requests AFTER INSERT OR DELETE OR UPDATE ON core."assessment_protocol_requests" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('request_id');
CREATE TRIGGER trg_updated_at_assessment_protocol_requests BEFORE UPDATE ON core."assessment_protocol_requests" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_ca_doctor_assignments AFTER INSERT OR DELETE OR UPDATE ON core."ca_doctor_assignments" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('cda_id');
CREATE TRIGGER trg_audit_clinic_requests AFTER INSERT OR DELETE OR UPDATE ON core."clinic_requests" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('request_id');
CREATE TRIGGER trg_updated_at_clinic_requests BEFORE UPDATE ON core."clinic_requests" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_clinic_staff_assignments AFTER INSERT OR DELETE OR UPDATE ON core."clinic_staff_assignments" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('assignment_id');
CREATE TRIGGER trg_audit_clinics AFTER INSERT OR DELETE OR UPDATE ON core."clinics" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('clinic_id');
CREATE TRIGGER trg_updated_at_clinics BEFORE UPDATE ON core."clinics" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_consent_records AFTER INSERT OR DELETE OR UPDATE ON compliance."consent_records" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('consent_id');
CREATE TRIGGER trg_audit_consent_templates AFTER INSERT OR DELETE OR UPDATE ON reference."consent_templates" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('template_id');
CREATE TRIGGER trg_audit_device_assignments AFTER INSERT OR DELETE OR UPDATE ON core."device_assignments" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('da_id');
CREATE TRIGGER trg_audit_doctor_patient_assignments AFTER INSERT OR DELETE OR UPDATE ON core."doctor_patient_assignments" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('assignment_id');
CREATE TRIGGER trg_audit_doctor_schedule_overrides AFTER INSERT OR DELETE OR UPDATE ON core."doctor_schedule_overrides" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('override_id');
CREATE TRIGGER trg_audit_doctor_session_notes AFTER INSERT OR DELETE OR UPDATE ON core."doctor_session_notes" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('note_id');
CREATE TRIGGER trg_updated_at_doctor_session_notes BEFORE UPDATE ON core."doctor_session_notes" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_doctor_weekly_schedules AFTER INSERT OR DELETE OR UPDATE ON core."doctor_weekly_schedules" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('schedule_id');
CREATE TRIGGER trg_updated_at_doctor_weekly_schedules BEFORE UPDATE ON core."doctor_weekly_schedules" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_doctors AFTER INSERT OR DELETE OR UPDATE ON core."doctors" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('doctor_id');
CREATE TRIGGER trg_updated_at_inventory BEFORE UPDATE ON core."inventory" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_notify_outbox_event AFTER INSERT ON ops."outbox_events" FOR EACH ROW EXECUTE FUNCTION ops.fn_notify_outbox_event();
CREATE TRIGGER trg_audit_patient_clinic_transfers AFTER INSERT OR DELETE OR UPDATE ON core."patient_clinic_transfers" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('pct_id');
CREATE TRIGGER trg_updated_at_patient_clinic_transfers BEFORE UPDATE ON core."patient_clinic_transfers" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_patient_disease_selection AFTER INSERT OR DELETE OR UPDATE ON core."patient_disease_selection" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('pds_id');
CREATE TRIGGER trg_updated_at_patient_disease_selection BEFORE UPDATE ON core."patient_disease_selection" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_patient_eeg_files AFTER INSERT OR DELETE OR UPDATE ON core."patient_eeg_files" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('eeg_id');
CREATE TRIGGER trg_updated_at_patient_eeg_files BEFORE UPDATE ON core."patient_eeg_files" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_patient_medical_history_files AFTER INSERT OR DELETE OR UPDATE ON core."patient_medical_history_files" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('mhf_id');
CREATE TRIGGER trg_updated_at_patient_medical_history_files BEFORE UPDATE ON core."patient_medical_history_files" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_patient_scale_assignments AFTER INSERT OR DELETE OR UPDATE ON core."patient_scale_assignments" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('psa_id');
CREATE TRIGGER trg_audit_patients AFTER INSERT OR DELETE OR UPDATE ON core."patients" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('patient_id');
CREATE TRIGGER trg_generate_mrn BEFORE INSERT ON core."patients" FOR EACH ROW EXECUTE FUNCTION core.fn_generate_mrn();
CREATE TRIGGER trg_updated_at_patients BEFORE UPDATE ON core."patients" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_payments AFTER INSERT OR DELETE OR UPDATE ON core."payments" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('payment_id');
CREATE TRIGGER trg_updated_at_payments BEFORE UPDATE ON core."payments" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_updated_at_products BEFORE UPDATE ON reference."products" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_profiles AFTER INSERT OR DELETE OR UPDATE ON core."profiles" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('id');
CREATE TRIGGER trg_updated_at_profiles BEFORE UPDATE ON core."profiles" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_prs_assessment_instances AFTER INSERT OR DELETE OR UPDATE ON core."prs_assessment_instances" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('instance_id');
CREATE TRIGGER trg_updated_at_prs_diseases BEFORE UPDATE ON reference."prs_diseases" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE CONSTRAINT TRIGGER trg_recalculate_final_result AFTER INSERT OR UPDATE ON core."prs_scale_results" DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION core.recalculate_final_result();
CREATE TRIGGER trg_updated_at_prs_scales BEFORE UPDATE ON reference."prs_scales" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_regions AFTER INSERT OR DELETE OR UPDATE ON core."regions" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('region_id');
CREATE TRIGGER trg_updated_at_regions BEFORE UPDATE ON core."regions" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_sessions AFTER INSERT OR DELETE OR UPDATE ON core."sessions" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('session_id');
CREATE TRIGGER trg_updated_at_sessions BEFORE UPDATE ON core."sessions" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_staff_requests AFTER INSERT OR DELETE OR UPDATE ON core."staff_requests" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('request_id');
CREATE TRIGGER trg_updated_at_staff_requests BEFORE UPDATE ON core."staff_requests" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_stock_transfers AFTER INSERT OR DELETE OR UPDATE ON core."stock_transfers" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('st_id');
CREATE TRIGGER trg_audit_store_orders AFTER INSERT OR DELETE OR UPDATE ON core."store_orders" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('order_id');
CREATE TRIGGER trg_updated_at_store_orders BEFORE UPDATE ON core."store_orders" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_treatment_cycles AFTER INSERT OR DELETE OR UPDATE ON core."treatment_cycles" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('cycle_id');
CREATE TRIGGER trg_updated_at_treatment_cycles BEFORE UPDATE ON core."treatment_cycles" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_treatment_plans AFTER INSERT OR DELETE OR UPDATE ON core."treatment_plans" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('plan_id');
CREATE TRIGGER trg_updated_at_treatment_plans BEFORE UPDATE ON core."treatment_plans" FOR EACH ROW EXECUTE FUNCTION ops.fn_set_updated_at();
CREATE TRIGGER trg_audit_treatment_sessions AFTER INSERT OR DELETE OR UPDATE ON core."treatment_sessions" FOR EACH ROW EXECUTE FUNCTION ops.fn_audit_trigger('ts_id');;
